waypoint_planner:
  ros__parameters:
    waypoint_graph_file: '/root/mfa_ws/src/aerial_waypoint_manager/waypoint_sampler/waypoint_graph.pkl'
    
    # Topics
    uav_gps_topic: '/mavros/global_position/global'
    uav_altitude_topic: '/mavros/global_position/rel_alt'
    goal_topic: 'waypoint_request'
    waypoint_response_topic: 'waypoint_response'
    setpoint_topic: '/mavros/setpoint_raw/global'
    land_topic: '~/land'
    state_topic: '~/state'
    
    # Takeoff
    takeoff_enabled: true
    use_takeoff_pos: true
    takeoff_latitude: 40.0
    takeoff_longitude: -74.0
    takeoff_altitude: 20.0
    
    # FSM
    fsm_rate: 20.0
    altitude_threshold: 0.2
    position_threshold: 2.0

waypoint_gui:
  ros__parameters:
    satellite_map_file: '/root/mfa_ws/src/aerial_waypoint_manager/waypoint_sampler/satellite_map.pkl'
